### ISSUE TITLE
Generic Property Types Not Properly Compared When Detecting Duplicate Keys

### ISSUE THREAD

**Issue by ReeseJones** [azixMcAze/SerializableDictionary#3]
I have a custom type which more or less encapsulates a string and its used as a key for a dictionary. Its definition looks like:

```CS
[Serializable]
public class DictionaryTypeObject : SerializableDictionary< SerializableType, UnityEngine.Object> { }
```

However when I try and use the inspector to add more than one element, nothing happens. I tracked down the issue to the following line in SerializableDictionaryPropertyDrawer

![image](https://user-images.githubusercontent.com/6557783/36626276-e9391dce-18e4-11e8-8758-96aabae03c58.png)

This works for non arrays/generic types. For generic properties which are managed as dictionaries in this implementation it's doing a reference comparison which will result in the equality check always being false. I haven't tested this for arrays types, but I assume it would be the same.

I tried this:
![image](https://user-images.githubusercontent.com/6557783/36626374-737f185c-18e6-11e8-8955-bd711028d1e3.png)

And then it started correctly identifying duplicate keys with generic serialized properties.

I don't know if this actually a good implementation or not, and I am pretty sure it still wont work with arrays. I also have no idea if it would still work with nested custom serializeable classes.

This is by far the best Serialized Dictionary Implementation I have come across for Unity though. Well done, saved me a lot of time.

**Comment by azixMcAze** [comment]
Hi,
Another user has reported a reported a similar problem. You have correctly identified the problem!
The comparison is not working properly and the property drawer fails to identify the conflict in the keys.

I think the solution to this problem would be to do recursive comparison of the dictionaries, like you did, with a few more checks (keys present in dict2 but not in dict1, and a recursive comparison if any of the key is also a string/object dictionary)

However, this comparison is not correct if the dictionary's `TKey` type implements `Equals()` or `GetHashCode()` because they will be used by the dictionary to compare the keys but not by the custom property drawer.
The correct solution would be to get the key values as a proper `TKey` instance instead of a `Dictionary<string, object>` instance.
This is not possible at the moment because the `SerializedProperty` class can only return values of simple types and cannot return the real type (a `Type` instance) of the property.

But a recursive dictionary comparison should work a lot better than the current implementation. 

I will be able to work again on SerializableDictionary soon.
Cheers and thank you for the kind words.
