### ISSUE TITLE
Problem of more than 12 KeyValuePairs

### ISSUE THREAD

**Issue by jack81722** [azixMcAze/SerializableDictionary#6]
Hi, azixMcAze:

I am very like your serialize dictionary idea. I recently found a problem that I can't add new element when the dictionary count is more than 12.  This problem always happened after build an APK. This situation also happened in your example scene. My unity version is 5.4.0f3. How could I fix the problem?

Error Message:
> IndexOutOfRangeException: Array index is out of range.
> System.Collections.Generic.Dictionary`2+Enumerator[System.String,System.String].MoveNext () (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:842)
> SerializableDictionary`2[TKey,TValue].OnBeforeSerialize () (at Assets/SerializableDictionary/SerializableDictionary.cs:60)
> UnityEditor.DockArea:OnGUI()

**Comment by jack81722** [comment]
Excuse me, I had try it in Unity 2017 version. It's no problem!

**Comment by azixMcAze** [comment]
Hi, I could indeed reproduce the problem with Unity 5.4
According to this [Stack Overflow question](https://stackoverflow.com/questions/36194178/unity-serialized-dictionary-index-out-of-range-after-12-items), it is caused by a bug in Unity that's fixed in Unity 2017.

I'm closing the issue because I don't see how I can workaround this bug for previous versions of Unity
